version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./server/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./server/src:/var/www/laravel
    depends_on:
      - mysql
      - php
      - vue
  php:
    build:
      context: server/dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./server/src:/var/www/laravel
  mysql:
    image: mysql:8.0
    ports:
      - "3316:3306"
    env_file:
      - server/env/mysql.env
    volumes:
      - ./server/db_data:/var/lib/mysql

  vue:
    build:
      context: client
      dockerfile: vue.Dockerfile
    volumes:
      - ./client/src:/var/www/vue
      - ./client/src/node_modules:/var/www/vue/node_modules
    ports:
      - "8080:8080"

  composer:
    build:
      context: server/dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./server/src:/var/www/laravel
  artisan:
    build:
      context: server/dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./server/src:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]

volumes:
  dbdata:
  node_modules:

